// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  posX: __t.f32(),
  posY: __t.f32(),
  posZ: __t.f32(),
  heading: __t.f32(),
  speed: __t.f32(),
  isBoosting: __t.bool(),
  isDrifting: __t.bool(),
  online: __t.bool(),
  lastUpdate: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const WorldState = __t.object("WorldState", {
  id: __t.u32(),
  weatherElapsedS: __t.f64(),
  dayTime: __t.f64(),
});
export type WorldState = __Infer<typeof WorldState>;

